apiVersion: batch/v1
kind: Job
metadata:
  name: JOB_NAME_PLACEHOLDER  # Placeholder for the job name
spec:
  template:
    spec:
      containers:
        - name: ml-container
          image: igorjsc/ml-image:latest
          volumeMounts:
            - name: shared-pvc
              mountPath: /mnt/data  # Mount PVC at /mnt/data
      restartPolicy: Never
      volumes:
        - name: shared-pvc
          persistentVolumeClaim:
            claimName: project2-pvc-igorcosta  # The PVC name

