apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job-$(date +%Y%m%d%H%M%S)  # Unique job name using timestamp
spec:
  template:
    spec:
      containers:
        - name: ml-container
          image: igorjsc/ml-image:latest
          volumeMounts:
            - name: shared-pvc
              mountPath: /mnt/data  # Mount PVC at /mnt/data
      restartPolicy: Never
      volumes:
        - name: shared-pvc
          persistentVolumeClaim:
            claimName: project2-pvc-igorcosta  # The PVC name

