apiVersion: apps/v1
kind: Deployment
metadata:
  name: igorcosta-playlist-recommender-deployment
  labels:
    app: igorcosta-playlist-recommender
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: igorcosta-playlist-recommender
  template:
    metadata:
      labels:
        app: igorcosta-playlist-recommender
    spec:
      containers:
        - name: recommender
          image: igorjsc/recommender:1.1
          ports:
            - containerPort: 52031
          volumeMounts:
            - name: project2-storage
              mountPath: /mnt/data  # This is the directory inside the container where the PVC will be mounted
          env:
            - name: DATABASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: dbpath # Name of the ConfigMap
                  key: DATABASE_PATH   # Key to retrieve from ConfigMap

            - name: RULES_PATH 
              valueFrom:
                configMapKeyRef:
                  name: dbpath # Name of the ConfigMap
                  key: RULES_PATH # Key to retrieve from ConfigMap
      volumes:
        - name: project2-storage
          persistentVolumeClaim:
            claimName: project2-pvc-igorcosta  # The name of the PVC

