apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: igorcosta
  name: project2-pvc-igorcosta
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class-igorcosta

