name: Run ML Job on db_pointer.yaml Change

on:
  push:
    paths:
      - config_files/db_pointer.yaml  # Trigger only when this file changes
      
permissions:                    # Global permissions configuration starts here
  contents: read                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests
  
jobs:
  run-ml-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          
      - name: Test Write Permissions
        run: |
          touch test-file.txt
          if [ -f "test-file.txt" ]; then
          echo "Write permissions are enabled."
          else
          echo "Write permissions are not enabled."
          fi
          ls -la

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Shell Script
        run: chmod +x ml-job-run.sh  # Ensure the script is executable

      - name: Run ML Job Script
        run: ./ml-job-run.sh


      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Auto updating ml-job.yaml"
          
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
