name: Run ML Job on db_pointer.yaml Change

on:
  push:
    paths:
      - config_files/db_pointer.yaml  # Trigger only when this file changes

jobs:
  run-ml-job:
    runs-on: ubuntu-latest

    steps:
      - name: Test Write Permissions
        run: |
          touch test-file.txt
          if [ -f "test-file.txt" ]; then
          echo "Write permissions are enabled."
          else
          echo "Write permissions are not enabled."
          fi
          ls -la

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Shell Script
        run: chmod +x ml-job-run.sh  # Ensure the script is executable

      - name: Run ML Job Script
        run: ./ml-job-run.sh
permissions:
  contents: write

